config/routes.rb
Rails.application.routes.draw do

   root "quotes#index"

  get "/contact" => "contact_forms#new", as: :contact
  post "/contact" => "contact_forms#create", as: :contact_forms
  get "/thanku" => "contact_forms#thanku", as: :thanku

    get "/quotes/tag/:tag_name" => "quotes#tagged", as: :quote_tag

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "dwightgnjohnson@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  acts_as_taggable
   include PgSearch
  pg_search_scope :search,
                against: [:quote, :author],
                using: {
                  tsearch: {dictionary: "english"}
                }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController

  def new
    @contact_form = ContactForm.new
  end

  def create
    @contact_form = ContactForm.new(params[:contact_form])
    if @contact_form.valid?
      @contact_form.deliver
      redirect_to thanku_path
    else
      render :new
    end
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  before_action do
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def index
    @quotes = Quote.all
    @quotes = @quotes.search(params[:search]) if params[:search].present?
  end


  def tagged
    @quotes = Quote.tagged_with(params[:tag_name])
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/contact_forms/new.html.erb
<%= simple_form_for @contact_form do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :message, as: :text %>
  <%= f.submit %>
<%end%>

app/views/contact_forms/thanku.html.erb
Thank u for emailing us!
<br><hr><br>
<%= link_to "Go to Homepage", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuoteApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= form_tag root_path, method: 'get' do %>
      <%= text_field_tag :search, params[:search] ,placeholder: "Search" %>
    <% end %>
    <%= link_to "Home", root_path %>
    <%= link_to "Contact Us", contact_path %>
    <br><br>
<%= yield %>

</body>
</html>

app/views/quotes/index.html.erb
<% @quotes.each do |x| %>
  <h3><%= x.quote %></h3>  -<em><%= x.author %></em>
  <% x.tags.each do |tag| %>
            <%= link_to tag.name, quote_tag_path(tag_name:tag.name) %>
          <% end %>
  <br><hr>
<%end%>